export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const CLEAR_POKEMON = 'CLEAR_POKEMON';
export const UPDATE_BAG = 'UPDATE_BAG';
export const TOGGLE_BAG = 'TOGGLE_BAG';